#!/usr/bin/env python3
"""Canonical semantic-progress builder with exact OGE 7.25 and accepted bounded subject/route overlays."""
from __future__ import annotations

import runpy
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
BASE = HERE / "build_russian_semantic_acceptance_progress_base.py"
INDIRECT_AUTHORITY = (
    HERE / "RUSSIAN-OGE-INDIRECT-SPEECH-EXACT-CANONICAL-COMPONENT-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_EXACT_OGE_INDIRECT_SPEECH_CANONICAL_COMPONENT_SLICE",
    1,
    "RUSSIAN_OGE_INDIRECT_SPEECH_EXACT_CANONICAL_COMPONENT_ACCEPTANCE_v0.1",
)
RU15_OGE_EXPOSITION_ROUTE_AUTHORITY = (
    HERE / "RU15-OGE-EXPOSITION-BOUNDED-ROUTE-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU15_OGE_EXPOSITION_BOUNDED_ROUTE_SEMANTICS",
    4,
    "RU15_OGE_EXPOSITION_BOUNDED_ROUTE_SEMANTIC_ACCEPTANCE_v0.1",
)
RU13_EXISTING_CANDIDATE_AUTHORITY = (
    HERE / "RU13-EXPRESSIVE-EXISTING-CANDIDATES-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU13_EXISTING_CANDIDATE_BOUNDED_SUBJECT_SEMANTICS",
    10,
    "RU13_EXPRESSIVE_EXISTING_CANDIDATES_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU01_PHONETICS_AUTHORITY = (
    HERE / "RU01-PHONETICS-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU01_PHONETICS_BOUNDED_SUBJECT_SEMANTICS",
    3,
    "RU01_PHONETICS_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU02_NORMATIVE_STRESS_AUTHORITY = (
    HERE / "RU02-NORMATIVE-STRESS-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU02_NORMATIVE_STRESS_BOUNDED_SUBJECT_SEMANTIC",
    1,
    "RU02_NORMATIVE_STRESS_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU03_PARONYM_AUTHORITY = (
    HERE / "RU03-PARONYM-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU03_PARONYM_BOUNDED_SUBJECT_SEMANTIC",
    1,
    "RU03_PARONYM_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU03_DICTIONARY_SENSE_AUTHORITY = (
    HERE / "RU03-DICTIONARY-SENSE-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU03_DICTIONARY_SENSE_BOUNDED_SUBJECT_SEMANTIC",
    1,
    "RU03_DICTIONARY_SENSE_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU03_DEFINITION_CONTEXT_AUTHORITY = (
    HERE / "RU03-DEFINITION-CONTEXT-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU03_DEFINITION_CONTEXT_BOUNDED_SUBJECT_SEMANTIC",
    1,
    "RU03_DEFINITION_CONTEXT_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU04_MORPHEMICS_AUTHORITY = (
    HERE / "RU04-MORPHEMICS-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU04_MORPHEMICS_BOUNDED_SUBJECT_SEMANTICS",
    3,
    "RU04_MORPHEMICS_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU05_WORDFORMATION_AUTHORITY = (
    HERE / "RU05-WORDFORMATION-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU05_WORDFORMATION_BOUNDED_SUBJECT_SEMANTICS",
    3,
    "RU05_WORDFORMATION_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU06_MORPHOLOGY_AUTHORITY = (
    HERE / "RU06-MORPHOLOGY-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU06_MORPHOLOGY_BOUNDED_SUBJECT_SEMANTICS",
    3,
    "RU06_MORPHOLOGY_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)
RU09_SYNTAX_AUTHORITY = (
    HERE / "RU09-SYNTAX-CANDIDATES-BOUNDED-SUBJECT-SEMANTIC-ACCEPTANCE-v0.1.json",
    "CENTRAL_BRAIN_ACCEPTED_RU09_SYNTAX_CANDIDATE_BOUNDED_SUBJECT_SEMANTICS",
    5,
    "RU09_SYNTAX_CANDIDATES_BOUNDED_SUBJECT_SEMANTIC_ACCEPTANCE_v0.1",
)

_namespace: dict[str, Any] = runpy.run_path(str(BASE))
_namespace["OBJECT_AUTHORITIES"] = tuple(_namespace["OBJECT_AUTHORITIES"]) + (INDIRECT_AUTHORITY,)
_namespace["ROUTE_SEMANTIC_AUTHORITIES"] = tuple(_namespace["ROUTE_SEMANTIC_AUTHORITIES"]) + (
    RU15_OGE_EXPOSITION_ROUTE_AUTHORITY,
)
_namespace["SUBJECT_SEMANTIC_AUTHORITIES"] = tuple(_namespace["SUBJECT_SEMANTIC_AUTHORITIES"]) + (
    RU13_EXISTING_CANDIDATE_AUTHORITY,
    RU01_PHONETICS_AUTHORITY,
    RU02_NORMATIVE_STRESS_AUTHORITY,
    RU03_PARONYM_AUTHORITY,
    RU03_DICTIONARY_SENSE_AUTHORITY,
    RU03_DEFINITION_CONTEXT_AUTHORITY,
    RU04_MORPHEMICS_AUTHORITY,
    RU05_WORDFORMATION_AUTHORITY,
    RU06_MORPHOLOGY_AUTHORITY,
    RU09_SYNTAX_AUTHORITY,
)
_namespace["build_progress"].__globals__["OBJECT_AUTHORITIES"] = _namespace["OBJECT_AUTHORITIES"]
_namespace["main"].__globals__["OBJECT_AUTHORITIES"] = _namespace["OBJECT_AUTHORITIES"]
_namespace["build_progress"].__globals__["ROUTE_SEMANTIC_AUTHORITIES"] = _namespace["ROUTE_SEMANTIC_AUTHORITIES"]
_namespace["main"].__globals__["ROUTE_SEMANTIC_AUTHORITIES"] = _namespace["ROUTE_SEMANTIC_AUTHORITIES"]
_namespace["build_progress"].__globals__["SUBJECT_SEMANTIC_AUTHORITIES"] = _namespace["SUBJECT_SEMANTIC_AUTHORITIES"]
_namespace["main"].__globals__["SUBJECT_SEMANTIC_AUTHORITIES"] = _namespace["SUBJECT_SEMANTIC_AUTHORITIES"]
_base_build_progress = _namespace["build_progress"]
_base_main = _namespace["main"]


def build_progress() -> dict[str, Any]:
    return _base_build_progress()


def main() -> int:
    return _base_main()


if __name__ == "__main__":
    raise SystemExit(main())
