import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import path from 'node:path';
import process from 'node:process';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');const port=41739;const server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function assert(c,m){if(!c)throw new Error(m)}
try{await sleep(900);const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(String(e)));await page.goto(`http://127.0.0.1:${port}/ege-khimiya-demoversiya-PREVIEW.html`,{waitUntil:'networkidle'});assert(await page.locator('#chem-start-btn').isVisible(),'start screen');await page.evaluate(()=>window.KhimiyaDemoTestApi.startWithVariants({'19':1,'20':1,'24':1,'25':1,'28':1}));assert(await page.locator('.chem-nav-btn').count()===34,'34 nav positions');const cases=await page.evaluate(()=>window.KhimiyaDemoTestApi.acceptance.filter(x=>x.task_number<=28));for(const c of cases){const got=await page.evaluate(c=>window.KhimiyaDemoTestApi.scoreShort(c.task_number,c.variant,c.input),c);assert(got===c.expected_score,`${c.id}: ${got} != ${c.expected_score}`)}
await page.locator('#chem-answer').fill('21');await sleep(100);assert(await page.locator('.chem-nav-btn[data-number="1"]').evaluate(e=>e.classList.contains('is-answered')),'answered state');await page.locator('#chem-flag').click();assert(await page.locator('.chem-nav-btn[data-number="1"]').evaluate(e=>e.classList.contains('is-flagged')),'flagged state');await page.reload({waitUntil:'networkidle'});assert((await page.locator('#chem-answer').inputValue())==='21','answer persisted');assert((await page.evaluate(()=>window.KhimiyaDemoTestApi.getSelectedTask(19).variant))===1,'variant persisted');
const dep=await page.evaluate(()=>window.KhimiyaDemoTestApi.normalizeCriteria(29,{equation:false,balance:true}));assert(dep.balance===false,'task29 dependency');const special34=await page.evaluate(()=>window.KhimiyaDemoTestApi.extScore(34,{_special:'single_calc_error',equations:true,calculations:true,logic:true,result:true}));assert(special34===3,'task34 official single calculation error branch');const normalized34=await page.evaluate(()=>window.KhimiyaDemoTestApi.normalizeCriteria(34,{_special:'single_calc_error',equations:true,calculations:true,logic:true,result:true}));assert(!normalized34.equations&&!normalized34.calculations&&!normalized34.logic&&!normalized34.result,'task34 special branch excludes ordinary element selection');await page.evaluate(()=>window.KhimiyaDemoTestApi.seedAllCorrect());const totals=await page.evaluate(()=>window.KhimiyaDemoTestApi.totals());assert(totals.short===36&&totals.extended===20&&totals.total===56,'maxima 36+20=56');await page.evaluate(()=>window.KhimiyaDemoTestApi.finishNow());assert((await page.locator('#chem-results').innerText()).includes('ориентировочная сумма'),'honest result label');assert(!(await page.locator('#chem-results').innerText()).includes('официальный итог'),'no false official total');
for(const w of [320,360,390,768,1280]){await page.setViewportSize({width:w,height:900});await sleep(80);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+1);assert(!overflow,`overflow ${w}`);if(process.env.CHEM_SCREENSHOT_DIR){await page.screenshot({path:path.join(process.env.CHEM_SCREENSHOT_DIR,`results-${w}.png`),fullPage:true})}}await page.locator('#chem-results [data-open-reference]').click();assert(await page.locator('#chem-ref-solubility').getAttribute('src').then(x=>x.startsWith('data:image/webp;base64,')),'embedded reference');assert(errors.length===0,`console errors: ${errors.join('; ')}`);await browser.close();console.log('browser_test: PASS')}finally{server.kill('SIGTERM')}
